### ISSUE TITLE
使用不太明确

### ISSUE THREAD

**Issue by cdtubear** [ao-space/gt#18]
从测试结果来看，或许gt在未来能取代frp，但网上的教程太少了，md文档里提供的配置不太明确，能提供简易的例子或提供docker镜像最好了，现在使用gt相较于frp学习成本较高

**Comment by vyloy** [comment]
感谢关注，gt 的初心不是取代谁啦。而是作为保护个人隐私的支点，支撑本地优先、Self-hosted 类应用的外网访问。

> gt 注重隐私保护，在保证满足功能实现需要的情况下，最少化 server 端对数据包的分析，例如：基于 TCP 连接的实现方式，应用层 HTTP 协议传输只分析第一个数据包的 HTTP 协议头的目标数据，不作任何多余分析，将后续数据直接转发。

学习成本方面，计划是会通过 #2 增加 web ui 来简化配置复杂度，用户不需要接触命令行参数、配置文件，就能使用。

**Comment by yuandaqing2009** [comment]
问题已解答，此issue关闭
