### ISSUE TITLE
GT server and GT client develop web management functions

### ISSUE THREAD

**Issue by aospace-admin** [ao-space/gt#2]
### Description

To improve the user experience, we plan to add web management functions for GT server and GT client respectively, supporting: administrator login, connection status view, configuration management, pprof, etc.

### Project output requirements

* Design and implement complete web management features: administrator login, connection status view, configuration management, pprof, etc.
* Write unit tests and integration tests
* Write appropriate design and usage documentation
* Focus on page user experience and page effects
* Code compliance with specifications: https://google.github.io/styleguide/go/, https://google.github.io/styleguide/htmlcssguide.html

### Project technical requirements

* Familiarity with Golang, HTML5, Javascript, CSS3
* Familiarity with vue3, element-ui framework
* Familiar with front-end page adaptation

[Open Source Summer Official Website](https://summer-ospp.ac.cn/)

### 描述

为了提高用户体验，计划分别为 GT server 和 GT client 增加 Web 管理功能，支持：管理员登录、连接状态查看，配置管理，pprof等

### 项目产出要求

* 设计并实现完善的 Web 管理功能：管理员登录、连接状态查看，配置管理，pprof等
* 编写相应的单元测试和集成测试
* 编写相应的设计和使用文档
* 注重页面用户体验、页面效果
* 代码符合规范： [https://google.github.io/styleguide/go/、https://google.github.io/styleguide/htmlcssguide.html](https://google.github.io/styleguide/go/%E3%80%81https://google.github.io/styleguide/htmlcssguide.html)

### 项目技术要求

* 熟悉 Golang、HTML5、Javascript、CSS3
* 熟悉 vue3、element-ui 框架
* 熟悉前端页面适配GT server 与 GT client 开发 Web 管理功能

[开源之夏官网](https://summer-ospp.ac.cn/)

**Comment by psankhe28** [comment]
I am interested for contributing to this project. Are there any specific tasks that need to be done?

**Comment by vyloy** [comment]
> I am interested for contributing to this project. Are there any specific tasks that need to be done?

Hi, @psankhe28 
It's great to hear from you. What kind of tasks do you like? Do you prefer front end tasks?

**Comment by psankhe28** [comment]
I am proficient in both front-end and back-end development, but I would prefer front-end tasks.

**Comment by vyloy** [comment]
@psankhe28 

Good. This project requires developers with full stack skills.

 Can you create a detailed proposal issue about how to design and complete this project before actually working on specific tasks?

**Comment by psankhe28** [comment]
Sure. I would work on it.

**Comment by psankhe28** [comment]
I had some doubts regarding the implementation and project.
1. Could you please provide more information about what is meant by the implementation of the "pprof" feature in this project?
2. Could you give me a brief overview of the requirements for "page effects" in this project, and what is expected to be implemented?
3. I am well versed with frontend and backend technologies but haven't use vue.js and Golang but I would love to learn and implement it in this project, would that be fine?

**Comment by vyloy** [comment]
> I had some doubts regarding the implementation and project.
> 
> 1. Could you please provide more information about what is meant by the implementation of the "pprof" feature in this project?
> 2. Could you give me a brief overview of the requirements for "page effects" in this project, and what is expected to be implemented?
> 3. I am well versed with frontend and backend technologies but haven't use vue.js and Golang but I would love to learn and implement it in this project, would that be fine?

@psankhe28 

1. Standard Library Package pprof serves via its HTTP server runtime profiling data in the format expected by the pprof visualization tool: <https://pkg.go.dev/net/http/pprof@go1.20.4> 
2. Currently GT can only be used from the command line, and as the number of parameters increases, it becomes more difficult to use. You can use GT for a while and then think about what you can do from the user's perspective to make it less difficult to use and improve the user experience while displaying important data if you add UI functionality to GT. Perhaps the answer will come.
3. That's totally fine! :)

**Comment by psankhe28** [comment]
Thank you for patiently answering all my queries.
