### ISSUE TITLE
TCP 内网穿透实测失败，有什么注意点？

### ISSUE THREAD

**Issue by mmabluesky** [ao-space/gt#25]
Hi ：
    根据文档，我尝试了下TCP 内网穿透这个示例 ，主要需求是通过ssh公网的某一个端口，访问内网， 实测一直提示ssh超时，

我的命令分别为：
./release/linux-amd64-server -addr 9527 -id id1 -secret secret1 -tcpNumber 1 -tcpRange 1024-65535
./release/linux-amd64-client -local http://127.0.0.1:22 -remote tcp://42.193.223.69:9527 -id id1 -secret secret1 -remoteTCPPort 2222

![image](https://github.com/ao-space/gt/assets/17948377/23a4cfd1-b131-40cd-b331-473b21695fa1)

**Comment by vyloy** [comment]
tcp 内网穿透需要使用最新版本。可以直接拉取容器：<https://github.com/ao-space/gt/blob/dev/README_CN.md#docker-%E5%AE%B9%E5%99%A8%E8%BF%90%E8%A1%8C>

建议使用配置文件的方式，可以参考配置文件例子：<https://github.com/ao-space/gt/blob/dev/README_CN.md#%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6>

`./release/linux-amd64-client -local http://127.0.0.1:22/ -remote tcp://42.193.223.69:9527 -id id1 -secret secret1 -remoteTCPPort 2222`

如果是 tcp 内网穿透，-local 应该写 tcp://127.0.0.1:22

**Comment by mmabluesky** [comment]
服务端报下面这个错，会是什么原因？提示34980端口打不开
./release/linux-amd64-server -config ./release/config/server.yaml
Tue Sep 12 20:10:43 CST 2023 INF linux-amd64-server - 2023-09-12 19:19:28 - dev 49eb106 config={"APIAddr":"","APICertFile":"","APIKeyFile":"","APITLSMinVersion":"tls1.2","Addr":"8081","AllowAnyClient":false,"AuthAPI":"","CertFile":"","Config":"./release/config/server.yaml","Connections":10,"HTTPMUXHeader":"Host","Host":{"Number":null,"Prefixes":null,"Regex":null,"RegexStr":null,"WithID":null},"HostNumber":0,"HostRegex":null,"HostWithID":false,"IDs":null,"KeyFile":"","LogFile":"","LogFileMaxCount":7,"LogFileMaxSize":536870912,"LogLevel":"info","MaxHandShakeOptions":30,"ReconnectDuration":300000000000,"ReconnectTimes":3,"SNIAddr":"","STUNAddr":"","STUNLogLevel":"warn","Secrets":null,"SentryDSN":"","SentryDebug":false,"SentryEnvironment":"","SentryLevel":null,"SentryRelease":"linux-amd64-server - 2023-09-12 19:19:28 - dev 49eb106","SentrySampleRate":1,"SentryServerName":"","Speed":0,"TCPNumber":0,"TCPRanges":null,"TCPs":null,"TLSAddr":"","TLSMinVersion":"tls1.2","Timeout":90000000000,"TimeoutOnUnidirectionalTraffic":false,"Users":{"id1":{"Connections":0,"Host":{"Number":null,"Prefixes":null,"Regex":null,"RegexStr":null,"WithID":null},"Secret":"secret1","Speed":0,"TCPNumber":null,"TCPs":[{"Range":"10000-15000"},{"Range":"20000-25000"}]}},"Version":"1.0"}
Tue Sep 12 20:10:43 CST 2023 INF Listening addr=[::]:8081
Tue Sep 12 20:10:43 CST 2023 INF acceptLoop started addr=[::]:8081
Tue Sep 12 20:11:04 CST 2023 INF accepted ip=113.116.177.93:34980 serverConn=c00033a000
Tue Sep 12 20:11:04 CST 2023 INF handling tunnel checksum=26dba56ece71ce95a195c1f93a46a048ad32a1cde67783217293f69e1c876785 ip=113.116.177.93:34980 reload=false serverConn=c00033a000 tunnel=2023-09-12T20:11:04+08:00
Tue Sep 12 20:11:04 CST 2023 INF updated tunnel host prefixes client=id1 ip=113.116.177.93:34980 old prefixes= prefixes= serverConn=c00033a000 tunnel=2023-09-12T20:11:04+08:00
Tue Sep 12 20:11:04 CST 2023 WRN **failed to open the tcp port user asked client=id1 ip=113.116.177.93:34980** port=2222 serverConn=c00033a000 tunnel=2023-09-12T20:11:04+08:00
Tue Sep 12 20:11:04 CST 2023 INF tcp port opened client=id1 ip=113.116.177.93:34980 port=14018 serverConn=c00033a000 tunnel=2023-09-12T20:11:04+08:00
Tue Sep 12 20:11:04 CST 2023 INF readLoop begin client=id1 ip=113.116.177.93:34980 serverConn=c00033a000 tunnel=2023-09-12T20:11:04+08:00
Tue Sep 12 20:11:04 CST 2023 INF acceptLoop started addr=[::]:14018

**Comment by mmabluesky** [comment]
还有这个容器如何加载我自己的配置文件呢

**Comment by vyloy** [comment]
> 服务端报下面这个错，会是什么原因？提示34980端口打不开 ./release/linux-amd64-server -config ./release/config/server.yaml Tue Sep 12 20:10:43 CST 2023 INF linux-amd64-server - 2023-09-12 19:19:28 - dev [49eb106](https://github.com/ao-space/gt/commit/49eb106c37365e18f004b527c089f78137524c0c) config={"APIAddr":"","APICertFile":"","APIKeyFile":"","APITLSMinVersion":"tls1.2","Addr":"8081","AllowAnyClient":false,"AuthAPI":"","CertFile":"","Config":"./release/config/server.yaml","Connections":10,"HTTPMUXHeader":"Host","Host":{"Number":null,"Prefixes":null,"Regex":null,"RegexStr":null,"WithID":null},"HostNumber":0,"HostRegex":null,"HostWithID":false,"IDs":null,"KeyFile":"","LogFile":"","LogFileMaxCount":7,"LogFileMaxSize":536870912,"LogLevel":"info","MaxHandShakeOptions":30,"ReconnectDuration":300000000000,"ReconnectTimes":3,"SNIAddr":"","STUNAddr":"","STUNLogLevel":"warn","Secrets":null,"SentryDSN":"","SentryDebug":false,"SentryEnvironment":"","SentryLevel":null,"SentryRelease":"linux-amd64-server - 2023-09-12 19:19:28 - dev [49eb106](https://github.com/ao-space/gt/commit/49eb106c37365e18f004b527c089f78137524c0c)","SentrySampleRate":1,"SentryServerName":"","Speed":0,"TCPNumber":0,"TCPRanges":null,"TCPs":null,"TLSAddr":"","TLSMinVersion":"tls1.2","Timeout":90000000000,"TimeoutOnUnidirectionalTraffic":false,"Users":{"id1":{"Connections":0,"Host":{"Number":null,"Prefixes":null,"Regex":null,"RegexStr":null,"WithID":null},"Secret":"secret1","Speed":0,"TCPNumber":null,"TCPs":[{"Range":"10000-15000"},{"Range":"20000-25000"}]}},"Version":"1.0"} Tue Sep 12 20:10:43 CST 2023 INF Listening addr=[::]:8081 Tue Sep 12 20:10:43 CST 2023 INF acceptLoop started addr=[::]:8081 Tue Sep 12 20:11:04 CST 2023 INF accepted ip=113.116.177.93:34980 serverConn=c00033a000 Tue Sep 12 20:11:04 CST 2023 INF handling tunnel checksum=26dba56ece71ce95a195c1f93a46a048ad32a1cde67783217293f69e1c876785 ip=113.116.177.93:34980 reload=false serverConn=c00033a000 tunnel=2023-09-12T20:11:04+08:00 Tue Sep 12 20:11:04 CST 2023 INF updated tunnel host prefixes client=id1 ip=113.116.177.93:34980 old prefixes= prefixes= serverConn=c00033a000 tunnel=2023-09-12T20:11:04+08:00 Tue Sep 12 20:11:04 CST 2023 WRN **failed to open the tcp port user asked client=id1 ip=113.116.177.93:34980** port=2222 serverConn=c00033a000 tunnel=2023-09-12T20:11:04+08:00 Tue Sep 12 20:11:04 CST 2023 INF tcp port opened client=id1 ip=113.116.177.93:34980 port=14018 serverConn=c00033a000 tunnel=2023-09-12T20:11:04+08:00 Tue Sep 12 20:11:04 CST 2023 INF readLoop begin client=id1 ip=113.116.177.93:34980 serverConn=c00033a000 tunnel=2023-09-12T20:11:04+08:00 Tue Sep 12 20:11:04 CST 2023 INF acceptLoop started addr=[::]:14018

这个是一个 warn 警告，后面的日志提示，已经开启了 14018 这个随机端口了，服务端的配置文件的允许范围不包括 34980 这个端口。

**Comment by vyloy** [comment]
> 还有这个容器如何加载我自己的配置文件呢

可以通过覆盖容器默认的 entrypoint ，并把配置文件映射到容器内，举个例子：
`docker run -it -v /user/config:/opt/config --entrypoint '/usr/bin/server -config /opt/config/server.yml' [docker_image]`

**Comment by mmabluesky** [comment]
感谢，这题没问题了 ，
