### ISSUE TITLE
[Feature] Support to be built and run on Windows

### ISSUE THREAD

**Issue by vyloy** [ao-space/gt#3]
Currently, GT can only be built and run on Linux or Linux Container. 

It would be great if GT supports to be built and run on Windows.

PR for this feature from new contributor are welcome.

**Comment by zhyueyueniao** [comment]
支持，有台windows服务员想装服务端都装不了

**Comment by vyloy** [comment]
预计下周发布新版本，会有 macOS 和 Windows 的版本。

**Comment by zhyueyueniao** [comment]
> 预计下周发布新版本，会有 macOS 和 Windows 的版本。

感谢大佬

**Comment by vyloy** [comment]
支持 macOS 和 Windows 的 v2.2.0 版本发布了：<https://github.com/ao-space/gt/releases/tag/v2.2.0>
