### ISSUE TITLE
远程协作场景需求请教

### ISSUE THREAD

**Issue by gotoeasy** [ao-space/gt#34]
远程协作场景：
1，有一台公网服务器，可以按需部署软件，域名server.example.com已解析关联，所有人都可以通过这个地址来访问。
2，员工远程办公，假设都在做web服务开发，每个人负责不同的部分。当他们完成自己的工作后，各自都在本地发布自己的服务。
3，服务有时需要相互调用，但由于环境各异不能直接互相访问，所以希望利用服务器作为中介，帮助它们相互通信。
4，有些员工在同一个办公室，他们希望能够在不改变开发方式的条件下，服务能自动发现并直接在局域网内部相互通信，而不是完全通过服务器，以提高速度。（这是画龙点睛功能，如果太难实现就不必坚持）
5，最后，测试人员或老板想要检查工作效果，他们不安装任何软件，只需在浏览器中访问 http(s)://server.example.com 就能查看系统的运行情况。

整个就像个把复杂的网络透明化的开发协作平台，此种需求是否有可能达成？

**Comment by vyloy** [comment]
> 远程协作场景：
1，有一台公网服务器，可以按需部署软件，域名server.example.com已解析关联，所有人都可以通过这个地址来访问。
2，员工远程办公，假设都在做web服务开发，每个人负责不同的部分。当他们完成自己的工作后，各自都在本地发布自己的服务。
3，服务有时需要相互调用，但由于环境各异不能直接互相访问，所以希望利用服务器作为中介，帮助它们相互通信。
4，有些员工在同一个办公室，他们希望能够在不改变开发方式的条件下，服务能自动发现并直接在局域网内部相互通信，而不是完全通过服务器，以提高速度。（这是画龙点睛功能，如果太难实现就不必坚持）
5，最后，测试人员或老板想要检查工作效果，他们不安装任何软件，只需在浏览器中访问 http(s)://server.example.com 就能查看系统的运行情况。

目前 1, 2, 3, 5 可以达成。4 未来会考虑支持。

HTTP(S)、WebSocket(S) 协议可以根据域名前缀，转发到对应的员工本地服务。
数据库、Redis、SSH等可以直接基于不同的 TCP 端口，转发到对应的员工本地服务。
