### ISSUE TITLE
对于页面提的几个建议

### ISSUE THREAD

**Issue by gituib** [ao-space/gt#41]
1.那这块如果不加server.yaml  默认使用127.0.0.1:8000   默认只能本机访问了吧，外网得话会无法访问，这一块希望在文档中能体现说明一下
2.希望页面端能添加修改端口得功能
3.希望页面端能添加修改域名证书得功能
4.希望页面端能添加页面多用户登录的功能，就比如我想共享给其他人使用  又不想给admin得账户 ，可以添加一个其他账户供使用

**Comment by vyloy** [comment]
建议4，未来会考虑把这个需求，设计成一个尽量简单易用的新功能。

目前主推通过 web ui 配置，建议1，2，3 应该已经可以满足了，可以体验一下新的 v2.2.0 版本。
